export const FETCH_COLLECTION_STARTED = 'FETCH_COLLECTION_STARTED';

export const FETCH_COLLECTION_FINISHED = 'FETCH_COLLECTION_FINISHED';

export const FETCH_COLLECTION_ERROR = 'FETCH_COLLECTION_ERROR';

export const SET_CURRENT_USER = 'SET_CURRENT_USER';

export const TOGGLE_CART_HIDDEN = 'TOGGLE_CART_HIDDEN';

export const ADD_CART_ITEM = 'ADD_CART_ITEM';

export const DEC_ITEM_COUNT = 'DEC_ITEM_COUNT';

export const REMOVE_CART_ITEM = 'REMOVE_CART_ITEM';

export const UPDATE_SHOP_DATA = 'UPDATE_SHOP_DATA';